language: java
# sudo: required instructs Travis to use a "real VM" instead of a docker VM
sudo: required
jdk:
- openjdk8
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq ant-optional
notifications:
  email:
    on_success: always
    on_failure: always
script:
- ./travis_checks.sh
